name: Bug report
description: Report a bug in Confkit
labels: [bug]
title: "bug: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug! Please fill out the details below to help us reproduce and fix the issue.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened…
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Provide a minimal reproduction if possible.
      placeholder: |
        1. Go to …
        2. Run …
        3. See error …
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior / logs
      render: shell
      placeholder: Include any stack traces or error messages
  - type: textarea
    id: code
    attributes:
      label: Relevant code / config
      description: Share snippets that demonstrate the issue
      render: shell
  - type: input
    id: versions
    attributes:
      label: Confkit package(s) and versions
      placeholder: e.g. confkit 0.x, @confkit/next 0.x, @confkit/aws 0.x
  - type: input
    id: node
    attributes:
      label: Node version
      placeholder: e.g. 18.20.4
  - type: input
    id: bun
    attributes:
      label: Bun version
      placeholder: e.g. 1.2.x
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: e.g. macOS 14.6, Ubuntu 22.04, Windows 11
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I have searched existing issues
          required: true
        - label: I am using the latest versions of Confkit packages

