blank_issues_enabled: false
contact_links:
  - name: Security report
    url: https://github.com/alexdotpink/confkit/security/advisories/new
    about: Please report security vulnerabilities privately via GitHub Security Advisories.
  - name: Documentation
    url: https://github.com/alexdotpink/confkit#readme
    about: Start with the README and in-repo docs.

