name: Pre-Release (next/beta)

on:
  push:
    branches:
      - next
  workflow_dispatch:
    inputs:
      tag:
        description: Dist tag for prerelease
        required: true
        default: next
        type: choice
        options:
          - next
          - beta

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.20

      - name: Install dependencies
        run: bun install --no-progress

      - name: Build
        run: bun run build

      - name: Publish prerelease tag
        run: |
          TAG=${{ github.event.inputs.tag || 'next' }}
          bun run release:publish:${TAG}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

